#!/usr/bin/env python3
"""Keep the generated in-app version constant synchronized with pubspec.yaml."""

from __future__ import annotations

import argparse
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
PUBSPEC = ROOT / "pubspec.yaml"
GENERATED = ROOT / "lib/src/app_version.g.dart"


def read_version() -> str:
    text = PUBSPEC.read_text(encoding="utf-8")
    match = re.search(r"^version:\s*([^\s#]+)", text, flags=re.MULTILINE)
    if match is None:
        raise RuntimeError("pubspec.yaml version was not found")
    return match.group(1)


def render(version: str) -> str:
    return (
        "// GENERATED FILE. Run `python3 tool/sync_app_version.py --write` "
        "after changing pubspec.yaml.\n"
        "// Do not edit this file manually.\n\n"
        f"const appVersion = '{version}';\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--write",
        action="store_true",
        help="rewrite the generated Dart file instead of checking it",
    )
    args = parser.parse_args()

    expected = render(read_version())
    if args.write:
        GENERATED.write_text(expected, encoding="utf-8")
        return 0

    actual = GENERATED.read_text(encoding="utf-8") if GENERATED.exists() else ""
    if actual != expected:
        print(
  "Displayed app version is out of sync. "
  "Run: python3 tool/sync_app_version.py --write",
  file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
